---
- hosts: localhost
  vars:
      source_key: "./.ssh/id_ed25519"
      dest_key: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/tools.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/work.yml
    - include_tasks: tasks/personal.yml
    - include_tasks: tasks/neovim.yml
